version: '3.3'

services:
  app:
    image: sistema_distancia_entre_cidades
    container_name: app
    ports: 
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/distanciaentrecidades
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - postgres-compose-network
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=controlegastos
    ports:
      - "5432:5432"
    volumes:
      - /home/filipemot/docker_data/distanciaentrecidades_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
