version: '3.3'

services:
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=distanciaentrecidades
    ports:
      - "5434:5432"
    volumes:
      - /home/filipemot/docker_data/distanciaentrecidades_data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-distanciaentrecidades-network-bd

networks: 
  postgres-compose-distanciaentrecidades-network-bd:
    driver: bridge
