TYPE_TEXT = 'Text'
TYPE_DOUBLE = 'Double'
TYPE_FLOAT = 'float'

FEATURE_CITY = 'city'
FEATURE_CITY_POINT = 'city_geo'
SHEET_NAME_CITY = 'municipios'
TABLE_CITY_POSTGRESQL = 'municipios'
FIELD_STATE = 'state'
FIELD_CITY_ID = 'Id'
FIELD_CITY_OBJECT_ID = 'OBJECTID'
FIELD_CITY_ID_STATE = 'Column6'
FIELD_CITY_LAT_STR = 'Column3'
FIELD_CITY_LNG_STR = 'Column4'
FIELD_CITY_LAT = 'X'
FIELD_CITY_LNG = 'Y'
FIELD_CITY_NAME = 'Column2'
FIELD_CITY_CODE_IBGE = 'Column1'
FIELD_CITY_CAPITAL = 'Column5'
FIELD_CITY_PHONE_NUMBER = 'Column8'

FIELD_CITY_ID_POSTGREE = 'id'
FIELD_CITY_NAME_POSTGREE = 'nome'
FIELD_CITY_ID_REFERENCE_POSTGREE = 'id_referencia'
FIELD_CITY_CODE_IBGE_POSTGREE = 'codigo_ibge'
FIELD_CITY_LAT_POSTGREE = 'latitude'
FIELD_CITY_LNG_POSTGREE = 'longitude'
FIELD_CITY_CAPITAL_POSTGREE = 'capital'
FIELD_CITY_STATE_POSTGREE = 'uf'
FIELD_CITY_CODE_PHONE_POSTGREE = 'ddd'

TABLE_DISTANCE_POSTGRESQL = 'distancias'

FEATURE_STATE = 'state'
SHEET_NAME_STATE = 'estados'
STATE_FIELD_ID = 'Column1'
STATE_FIELD_UF = 'Column2'

TYPE_LIST_DATASETS = 'ALL'

LICENCE_AVAILABLE = 'Available'

NETWORK_ANALYTICS_LICENCE = 'network'
NETWORK_ANALYTICS_IGNORE_INVALID_LOCATIONS = 'SKIP'
NETWORK_ANALYTICS_TERMINATE_ON_ERROR = 'TERMINATE'
NETWORK_ANALYTICS_DATASET_NAME = 'ODCostMatrixSolver*'
DISTANCE_MATRIX_IGNORE_INVALID_LOCATIONS = 'SKIP'

NETWORK_ANALYTICS_ORIGIN_TYPE = 'Origins'

NETWORK_ANALYTICS_ORIGIN_FIELD_MAPPING = 'Name Id #;TargetDestinationCount # #;CurbApproach # 0;Cutoff_Minutes # ' \
                                         '#;Cutoff_TravelTime # #;Cutoff_Miles # #;Cutoff_Kilometers # ' \
                                         '#;Cutoff_TimeAt1KPH # #;Cutoff_WalkTime # #;Cutoff_TruckMinutes # ' \
                                         '#;Cutoff_TruckTravelTime # # '
NETWORK_ANALYTICS_ORIGIN_SEARCH_TOLERANCE = '5000 Meters'

NETWORK_ANALYTICS_ORIGIN_SEARCH_CRITERIA = 'Routing_Streets SHAPE;Routing_Streets_Override NONE;Routing_ND_Junctions ' \
                                           'NONE '
NETWORK_ANALYTICS_ORIGIN_FIND_CLOSEST = 'MATCH_TO_CLOSEST'
NETWORK_ANALYTICS_ORIGIN_APPEND_LOCATION = 'APPEND'
NETWORK_ANALYTICS_ORIGIN_SNAP = 'NO_SNAP'
NETWORK_ANALYTICS_ORIGIN_SNAP_OFFSET = '5 Meters'
NETWORK_ANALYTICS_ORIGIN_EXCLUDE_RESTRICTED = 'EXCLUDE'

NETWORK_ANALYTICS_DESTINATION_TYPE = 'Destinations'
NETWORK_ANALYTICS_DESTINATION_FIELD_MAPPING = 'Name Id #;CurbApproach # 0'
NETWORK_ANALYTICS_DESTINATION_SEARCH_TOLERANCE = '5000 Meters'
NETWORK_ANALYTICS_DESTINATION_SEARCH_CRITERIA = 'Routing_Streets SHAPE;Routing_Streets_Override NONE;' \
                                            'Routing_ND_Junctions NONE'
NETWORK_ANALYTICS_DESTINATION_FIND_CLOSEST = 'MATCH_TO_CLOSEST'
NETWORK_ANALYTICS_DESTINATION_APPEND_LOCATION = 'APPEND'
NETWORK_ANALYTICS_DESTINATION_SNAP = 'NO_SNAP'
NETWORK_ANALYTICS_DESTINATION_SNAP_OFFSET = '5 Meters'
NETWORK_ANALYTICS_DESTINATION_EXCLUDE_RESTRICTED = 'EXCLUDE'

DISTANCE_MATRIX_LAYER_NAME = 'OD Cost Matrix'
DISTANCE_MATRIX_TRAVEL_MODE = 'Driving Distance'
DISTANCE_MATRIX_TIME_ZONE = 'LOCAL_TIME_AT_LOCATIONS'
DISTANCE_MATRIX_LINE_SHAPE = 'STRAIGHT_LINES'
DISTANCE_MATRIX_ACCUMULATE_ATTRIBUTES = 'Kilometers;Miles;Minutes;TimeAt1KPH;TravelTime;TruckMinutes;TruckTravelTime' \
                                      ';WalkTime '
DISTANCE_MATRIX_RESULTS_LAYER_NAME = 'distance_calculate'

